@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZTFlZDdhODcyYTQ5NzE1NDhmY2QyYSIsImlhdCI6MTc3NjQxNDMwNiwiZXhwIjoxNzc2NDIxNTA2fQ.nehP3i3DT4XmMjI17P1jJqSsICX7HzhkMhAdfY1m4ls

### Registro
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "LigmaBalls777",
    "email": "ligmaballs777@yopmail.xd",
    "password": "contrasegna",
    "online": false
}

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "ligmaballs777@yopmail.xd",
    "password": "contrasegna"
}

### Obtener perfil del usuario actual
GET http://localhost:3000/api/auth/me
Authorization: Bearer {{token}}

### Obtener salas
GET http://localhost:3000/api/rooms
Authorization: Bearer {{token}}

### Crear sala
POST http://localhost:3000/api/rooms
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Sala 2",
    "description": "Sala 2"
}

### Obtener mensajes de una sala
GET http://localhost:3000/api/rooms/69dbaed38d4373b4e679999d/messages
Authorization: Bearer {{token}}

### Editar mensaje
PUT http://localhost:3000/api/rooms/69dbaed38d4373b4e679999d/messages/69e1ed86f1f6d43c6a098938
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "content": "Mensaje editado"
}

### Borrar mensaje
DELETE http://localhost:3000/api/rooms/69dbaed38d4373b4e679999d/messages/69e1ed86f1f6d43c6a098938
Authorization: Bearer {{token}}