@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OWVmOWM3ZTVkN2UwMDk2ZjY2N2JiMjQiLCJzZXNzaW9uSWQiOiI2OWYwNzU1NDVkN2UwMDk2ZjY2N2JiMmQiLCJpYXQiOjE3NzczNjYzNTYsImV4cCI6MTc3NzQ1Mjc1Nn0.Y0SjtvQM-68sLqTaNPlhBZNrIbZTI9q109PvGBTXWlc
@refreshToken = 5f7db270eeb999aabe022fa3d1c0b6f84556684c05a910c0f8fcc73316e296a36406b27d001d2a48180c2084aef11f7fff1059629137401ca8aa054f25b13bd5
// El token debe ir arriba

### Health Check
GET https://repoprograwebservidor-production.up.railway.app/health

### Registrar usuario (hay que verificarlo) (por defecto es admin)
POST https://repoprograwebservidor-production.up.railway.app/api/user/register
Content-Type: application/json

{
    "email": "eeeeeee@gmail.com",
    "password": "ññññññññ",
    "name": "ññ",
    "lastName": "ññ",
    "nif": "12345678X",
    "role": "guest",
    "address": {
        "street": "Calle WakaWaka",
        "number": 2525,
        "postal": 28001,
        "city": "Madrid",
        "province": "Madrid"
    }
}

### Verificar al usuario que tiene el token
PUT https://repoprograwebservidor-production.up.railway.app/api/user/verify
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "verificationCode": 313723
}

### Login
### No utiliza el token ni tampoco ningún middleware
POST https://repoprograwebservidor-production.up.railway.app/api/user/login
Content-Type: application/json

{
    "email": "pacman@namco.com",
    "password": "xdxdxdxd"
}

### Actualizar el usuario que tiene el token
### PUT normalmente borra los campos que faltan
### pero aquí no porque estoy usando Object.assign
PUT https://repoprograwebservidor-production.up.railway.app/api/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Vegetta",
    "lastName": "777",
    "nif": "12345678A",
    "address": {
        "street": "Calle Ñ",
        "number": 123,
        "postal": 28001,
        "city": "Madrid",
        "province": "Madrid"
    }
}

### Cambiar solo la contraseña de un usuario
PATCH https://repoprograwebservidor-production.up.railway.app/api/user/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "oldPassword": "QueVivaElMaincra69@",
    "password": "vetr7n8y0rvtey7n8cwty7n90wtrvy7n0c8y890ecnrtwy7new0ctv07ecwtnvy8"
}

### Meter a un usuario en una compañía
### Si el ID no existe, crea una compañía freelance
### Pero si sí existe, el usuario pasa a ser guest
PATCH https://repoprograwebservidor-production.up.railway.app/api/user/company
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "company": "69d0e7e4d06b8140f7fc6609"
}

### Obtener usuarios (ruta protegida)
GET https://repoprograwebservidor-production.up.railway.app/api/user
Authorization: Bearer {{token}}

### Obtener los datos del usuario que tiene el token
GET https://repoprograwebservidor-production.up.railway.app/api/user/me
Authorization: Bearer {{token}}


### Refrescar el access token
POST https://repoprograwebservidor-production.up.railway.app/api/user/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

### Cerrar sesión (manda a tomar por culo ambos tokens)
POST https://repoprograwebservidor-production.up.railway.app/api/user/logout
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}

### Cerrar todas las sesiones (necesita accessToken)
POST https://repoprograwebservidor-production.up.railway.app/api/user/logout-all
Authorization: Bearer {{token}}

### Borrar usuario por ID
#DELETE http://localhost/api/user?soft=false
#Authorization: Bearer {{token}}
#Content-Type: application/json

#{
#    "id": "69d0d997603bbddcb8b9292f"
#}

### Soft delete
DELETE https://repoprograwebservidor-production.up.railway.app/api/user?soft=true
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": "69d0dac112c27a9a11bffbb4"
}

### Restaurar un usuario que fue soft deleteado
PUT https://repoprograwebservidor-production.up.railway.app/api/user/restore
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "id": "69d0dac112c27a9a11bffbb4"
}

### Crear compañía (ruta protegida)
POST https://repoprograwebservidor-production.up.railway.app/api/company
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Mi Empresa",
    "cif": "E12345678",
    "address": {
        "street": "Calle Falsa",
        "number": 123,
        "postal": 28001,
        "city": "Madrid",
        "province": "Madrid"
    }
}

### Actualizar compañía (ruta protegida)
PUT https://repoprograwebservidor-production.up.railway.app/api/company/69d0dbd364ffef7c376a4d4c
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Mi Empresa Actualizada",
    "cif": "E12345678",
    "address": {
        "street": "Calle Falsa",
        "number": 123,
        "postal": 28001,
        "city": "Madrid",
        "province": "Madrid"
    }
}

### Subir el logo de la compañía con Multer
### Esto lo que hace es coger el archivo de Content-Disposition y guardarlo en storage
PATCH https://repoprograwebservidor-production.up.railway.app/api/company/logo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="logo"; filename="test_logo.png"
Content-Type: image/png

< ./test_logo.png
------WebKitFormBoundary--

### Obtener compañías (ruta protegida)
GET https://repoprograwebservidor-production.up.railway.app/api/company
Authorization: Bearer {{token}}

### Soft delete de la compañía (ruta protegida)
DELETE https://repoprograwebservidor-production.up.railway.app/api/company/69d0dbd364ffef7c376a4d4c?soft=true
Authorization: Bearer {{token}}

### Hard delete de la compañía (ruta protegida)
DELETE https://repoprograwebservidor-production.up.railway.app/api/company/69d0dbd364ffef7c376a4d4c?soft=false
Authorization: Bearer {{token}}

### Invitar a un usuario
### Consiste en crear un nuevo usuario con los datos del JSON y meterle en la compañía del usuario que tiene el token
### El que invita debe ser admin
POST https://repoprograwebservidor-production.up.railway.app/api/user/invite
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "email": "email@address.com",
    "name": "Email",
    "lastName": "Address",
    "nif": "12345678A",
    "address": {
        "street": "Calle X",
        "number": 123,
        "postal": 28001,
        "city": "Madrid",
        "province": "Madrid"
    }
}

###########################################################################
### A partir de aquí es la práctica final

### Crear cliente
### No puede haber un cliente con el mismo CIF en esa compañía
POST https://repoprograwebservidor-production.up.railway.app/api/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cliente 1",
    "cif": "C1",
    "email": "cliente@cliente.com",
    "phone": "123456789",
    "address": {
        "street": "Calle 1",
        "number": 1,
        "postal": "12345",
        "city": "Ciudad 1",
        "province": "Provincia 1"
    }
}

### Actualizar un cliente por ID
PATCH https://repoprograwebservidor-production.up.railway.app/api/client/69ee0eac2b5a55f20eed61ba
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Cliente 1 Actualizado",
    "email": "clienteactualizado@clienteactualizado.com"
}

### Obtener todos los clientes
GET https://repoprograwebservidor-production.up.railway.app/api/client
Authorization: Bearer {{token}}

### Obtener un cliente por ID
GET https://repoprograwebservidor-production.up.railway.app/api/client/69edf0d72b5a55f20eed61a9
Authorization: Bearer {{token}}

### Borrar un cliente
DELETE https://repoprograwebservidor-production.up.railway.app/api/client/69ee0eac2b5a55f20eed61ba
Authorization: Bearer {{token}}

### Archivar un cliente (soft delete)
PATCH https://repoprograwebservidor-production.up.railway.app/api/client/69edf0d72b5a55f20eed61a9/archive
Authorization: Bearer {{token}}

### Restaurar un cliente archivado
PATCH https://repoprograwebservidor-production.up.railway.app/api/client/69edf0d72b5a55f20eed61a9/restore
Authorization: Bearer {{token}}

### Obtener solo los clientes archivados
GET https://repoprograwebservidor-production.up.railway.app/api/client/archived
Authorization: Bearer {{token}}


### Crear proyecto
### Tanto el usuario que lo creó como el cliente deben ser de la misma compañía
POST https://repoprograwebservidor-production.up.railway.app/api/project
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Proyecto 1",
    "projectCode": "P1",
    "client": "69edf0d72b5a55f20eed61a9",
    "email": "proyecto2@maincra.com",
    "notes": "qwertyuiopasdfghjklñzxcvbnm"
}

### Actualizar proyecto
PATCH https://repoprograwebservidor-production.up.railway.app/api/project/69ee0eac2b5a55f20eed61bc
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Proyecto 1 Actualizado",
    "client": "69ee0eac2b5a55f20eed61ba"
}

### Obtener todos los proyectos
GET https://repoprograwebservidor-production.up.railway.app/api/project
Authorization: Bearer {{token}}

### Obtener un proyecto por ID
GET https://repoprograwebservidor-production.up.railway.app/api/project/69ee2438ae9477fa1b3e3444
Authorization: Bearer {{token}}

### Borrar un proyecto
DELETE https://repoprograwebservidor-production.up.railway.app/api/project/69ee2438ae9477fa1b3e3444
Authorization: Bearer {{token}}

### Archivar un proyecto (soft delete)
PATCH https://repoprograwebservidor-production.up.railway.app/api/project/69ee2438ae9477fa1b3e3444/archive
Authorization: Bearer {{token}}

### Restaurar un proyecto eliminado
PATCH https://repoprograwebservidor-production.up.railway.app/api/project/69ee2438ae9477fa1b3e3444/restore
Authorization: Bearer {{token}}

### Obtener solo los proyectos archivados
GET https://repoprograwebservidor-production.up.railway.app/api/project/archived
Authorization: Bearer {{token}}


### Crear albarán
POST https://repoprograwebservidor-production.up.railway.app/api/deliveryNote
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "client": "69ef81274f98f406c641b41d",
    "project": "69ef81274f98f406c641b421",
    "format": "material",
    "description": "Materia",
    "quantity": "2",
    "signature": null
}

### Firmar (actualizar) un albarán y también subir una foto del albarán firmado
PATCH https://repoprograwebservidor-production.up.railway.app/api/deliveryNote/69f07a50804418f096e0315b
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="signature"; filename="signed_image.png"
Content-Type: image/png

< ./signed_image.png
------WebKitFormBoundary--


### Obtener todos los albaranes (con filtros)
GET http://localhost:3000/api/deliveryNote?company=69f07a0f804418f096e03153
Authorization: Bearer {{token}}

### Obtener un albarán por ID
GET https://repoprograwebservidor-production.up.railway.app/api/deliveryNote/69ef81284f98f406c641b425
Authorization: Bearer {{token}}

### Borrar un albarán (aquí no hay soft delete)
DELETE https://repoprograwebservidor-production.up.railway.app/api/deliveryNote/69ef81284f98f406c641b425
Authorization: Bearer {{token}}

### Descargar un albarán en PDF
GET https://repoprograwebservidor-production.up.railway.app/api/deliveryNote/pdf/69ef81284f98f406c641b425
Authorization: Bearer {{token}}
Accept: application/pdf


### Ruta para probar que Slack funciona
### GET https://repoprograwebservidor-production.up.railway.app/api/test/bug