@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxNSwiaWF0IjoxNzc1MDYyMTU0fQ.bPcam6S2-QGWnfWWwEVNEyOUjeATlFDVjIT5v6WabFY
@tokenLibrarian = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoyLCJpYXQiOjE3NzQ3MTkzMDB9.gOlo8L_oEHZWKysGb3sLg9X_sJUD3vWXTleJSAAqHR0
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjozLCJpYXQiOjE3NzQ4OTQ0NTJ9.W6Ok7HGLX4jDnBjN3gg21P7g9W6sWh79qVd5MIeXYmM

### Registrar usuario normal
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Willyrex",
    "email": "willyrex@ejemplo.com",
    "password": "contraseña",
    "role": "USER"
}

### Registrar usuario librarian
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Librarian",
    "email": "librarian@librarian.com",
    "password": "contraseña",
    "role": "LIBRARIAN"
}

### Registrar usuario admin
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin@admin.com",
    "password": "contraseña",
    "role": "ADMIN"
}

### Login usuario normal
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "juan@ejemplo.com",
    "password": "contraseña"
}

### Login usuario librarian
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "librarian@librarian.com",
    "password": "contraseña"
}

### Login usuario admin
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "contraseña"
}

### Me
GET http://localhost:3000/api/auth/me
//Authorization: Bearer {{token}}
//Authorization: Bearer {{tokenLibrarian}}
Authorization: Bearer {{tokenAdmin}}


### Obtener todos los libros (con paginación por defecto)
GET http://localhost:3000/api/books

### Obtener libros (página 2, límite 5)
GET http://localhost:3000/api/books?page=2&limit=5

### Obtener solo los libros de género "Libro"
GET http://localhost:3000/api/books?genre=Libro

### Obtener solo los libros hechos por Dross
GET http://localhost:3000/api/books?author=Dross

### Obtener solo los libros con copias disponibles
// De momento nada

### Obtener un libro por ID
GET http://localhost:3000/api/books/1

### Crear un libro (necesario ser librarian o admin)
POST http://localhost:3000/api/books
Content-Type: application/json
Authorization: Bearer {{tokenLibrarian}}

{
    "isbn": "666-6-66-666666-6",
    "title": "La Guerra de Ysak",
    "author": "Dross",
    "genre": "Libro",
    "description": "No sé",
    "publishedYear": 2015,
    "copies": 10,
    "availableCopies": 10
}

### Actualizar un libro (necesario ser librarian o admin)
PUT http://localhost:3000/api/books/1
Content-Type: application/json
Authorization: Bearer {{tokenLibrarian}}

{
    "title": "Wigetta 2",
    "author": "Willyrex y Vegetta",
    "genre": "Novela",
    "description": "La secuela del mejor libro jamás hecho",
    "publishedYear": 2015
}

### Eliminar un libro (necesario ser admin)
DELETE http://localhost:3000/api/books/1
Authorization: Bearer {{tokenAdmin}}


### Solicitar un préstamo
POST http://localhost:3000/api/loans
Content-Type: application/json
Authorization: Bearer {{tokenLibrarian}}

{
    "bookId": 12,
    "loanDate": "2022-01-01",
    "dueDate": "2022-01-15",
    "returnedDate": null,
    "status": "PENDING"
}

### Obtener todos los préstamos del usuario que es el dueño del token
GET http://localhost:3000/api/loans
Authorization: Bearer {{token}}

### Obtener todos los préstamos de todos los usuarios (necesario ser librarian o admin)
GET http://localhost:3000/api/loans/all
Authorization: Bearer {{tokenLibrarian}}

### Devolver un préstamo
PUT http://localhost:3000/api/loans/37/return
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "returnedDate": "2022-01-10",
    "status": "RETURNED"
}


### Obtener todas las reseñas de un libro
GET http://localhost:3000/api/books/1/reviews

### Crear una reseña para el libro 1 del usuario que tiene el token
POST http://localhost:3000/api/books/12/reviews
Content-Type: application/json
Authorization: Bearer {{tokenLibrarian}}

{
    "rating": 5,
    "comment": "Excelente libro"
}

### Actualizar una reseña
PUT http://localhost:3000/api/books/1/reviews
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "rating": 1,
    "comment": "Mierdón de libro"
}

### Eliminar una reseña
DELETE http://localhost:3000/api/reviews/1
Authorization: Bearer {{token}}


### Obtener los N libros más alquilados
GET http://localhost:3000/api/books/most-rented?limit=5

### Obtener los N libros mejor valorados
GET http://localhost:3000/api/books/best-rated?limit=5